"""Pure stop classification for dual-arm safety-state transitions."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from vr_rm75_teleop.safety_supervisor import SafetyDecision, SafetyState


class StopClass(str, Enum):
    """Software stop strength; neither class is a physical emergency stop."""

    CONTROLLED_STOP = "CONTROLLED_STOP"
    SAFETY_STOP = "SAFETY_STOP"


@dataclass(frozen=True)
class StopRequest:
    """One edge-triggered request generated by a safety-state transition."""

    stop_class: StopClass
    reason: str
    requested_monotonic: float


CONTROLLED_HOLD_REASONS = frozenset(
    {
        "deadman released",
    }
)


def stop_for_transition(
    decision: SafetyDecision,
    requested_monotonic: float,
) -> Optional[StopRequest]:
    """Map one ENGAGED exit edge to a controlled or safety stop."""
    if decision.previous_state != SafetyState.ENGAGED:
        return None
    if decision.state not in (SafetyState.HOLD, SafetyState.FAULT):
        return None

    controlled_hold = decision.state == SafetyState.HOLD
    if controlled_hold:
        controlled_hold = decision.reason in CONTROLLED_HOLD_REASONS
    if controlled_hold:
        stop_class = StopClass.CONTROLLED_STOP
    else:
        stop_class = StopClass.SAFETY_STOP
    return StopRequest(
        stop_class=stop_class,
        reason=decision.reason,
        requested_monotonic=float(requested_monotonic),
    )
