controller_joint_names:
  - wr_joint
  - wl_joint
  - xt_joint_1
  - xt_joint_2
  - dt_joint
  - yb_joint
  - xb_joint
  - jb_joint
  - tb_joint
  - l_rm75_joint_1
  - l_rm75_joint_2
  - l_rm75_joint_3
  - l_rm75_joint_4
  - l_rm75_joint_5
  - l_rm75_joint_6
  - l_rm75_joint_7
  - r_rm75_joint_1
  - r_rm75_joint_2
  - r_rm75_joint_3
  - r_rm75_joint_4
  - r_rm75_joint_5
  - r_rm75_joint_6
  - r_rm75_joint_7
  - wc_front_left_joint
  - wc_rear_left_joint
  - wc_rear_right_joint
  - wc_front_right_joint
